# Generated by Django 5.0.3 on 2026-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_conferenceitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceitem',
            name='session_title',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
